	
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: server
          image: swapnabadave/complex_api
          ports:
            - containerPort: 5000
          resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
 
# TODO: Add Env Vars for Postgres